### ISSUE TITLE
Intellij running an individual test

### ISSUE THREAD

**Issue by dadowns** [bechte/junit-hierarchicalcontextrunner#19]
Running Java 8, Intellij 14, junit 4.12. There appears to be a disconnect between intellij and junit for running a single test in a sub class. When I right click inside a method that's in a sub class I only see the option to run the whole outer test class. Its the same when using the Structure view. 

Curious if there's a way to get intellij to recognize that the sub classes have runnable tests and to just run/debug that single sub test?

Baring that one case, everything else works fine.

Example:
```
@RunWith(HierarchicalContextRunner.class)
public class OuterClassTest {
    @Test
    public void testMe() {
        assertTrue(true); // right clicking here shows "Run testMe()"
    }

    public class SubTests {
        @Test
        public void testSub() {
            assertTrue(true); // right clicking here shows "Run OuterClassTest"
        }
    }
}
```

**Comment by bechte** [comment]
Hi Dan,

this is a known (still frustrating) issue. Unfortunately, the tools do not support to run a single test within an inner class. I think this is due to the fact that JUnit never supported tests like this. Please see also issues #6 and #13 which deal with the same issue within eclipse.

I am sorry, that I cannot fix this behavior. It probably would need some of the IntelliJ guys to take a look at this.

All the best, Stefan

**Comment by dadowns** [comment]
No problem, that's what my guess was but I wanted to make sure. Thanks for the reply.

**Comment by bechte** [comment]
You're welcome.
